#include "system_digital_tube.h"


void Tube_Init_Config ( void )
{
	P1M0 = 0XC1;                        //设置成推挽输出
	P1M1 = 0XC1;                        //设置成推挽输出
	P1M2 = 0XC1;                        //设置成推挽输出
	P1M3 = 0XC1;						//设置成推挽输出
	P1M4 = 0XC1; 					   //设置成推挽输出
	P1M5 = 0XC1; 					   //设置成推挽输出
	P1M6 = 0XC1;						  //设置成推挽输出
	P0M4 = 0XC1;						  //设置成推挽输出
	P0M5 = 0XC1; 					   //设置成推挽输出
	P0M6 = 0XC1;						  //设置成推挽输出
	P0M7 = 0XC1; 					   //设置成推挽输出
}

static void digital_tube_set_num ( u8 num )
{
	switch ( num )
	{
		case 0:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_OFF;
			break;

		case 1:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 2:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 3:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 4:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 5:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 6:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 7:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 8:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;

		case 9:
			DIGITAL_TUBE_A = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_B = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_C = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_D = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_E = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_F = DIGITAL_TUBE_PIN_ON;
			DIGITAL_TUBE_G = DIGITAL_TUBE_PIN_ON;
			break;
	}


}

}

